# Generated by Django 6.0.7 on 2026-08-12 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='keywords',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='projects',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='resume_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='tags',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='ats_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='matched_skills',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='matching_percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='missing_skills',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='qualification',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='skills',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
