# Generated by Django 6.1 on 2026-08-28 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(max_length=100)),
                ('level', models.CharField(default='Beginner', max_length=50)),
                ('learning_order', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='LearningResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('resource_type', models.CharField(default='Course', max_length=50)),
                ('url', models.URLField(blank=True)),
                ('duration', models.CharField(blank=True, max_length=100)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='skillgap.skill')),
            ],
        ),
        migrations.CreateModel(
            name='JobRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('required_skills', models.ManyToManyField(to='skillgap.skill')),
            ],
        ),
    ]
