# Generated by Django 6.0.7 on 2026-07-29 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('salary', models.CharField(max_length=50)),
                ('job_type', models.CharField(choices=[('Full-Time', 'Full-Time'), ('Part-Time', 'Part-Time'), ('Internship', 'Internship')], max_length=20)),
                ('experience', models.CharField(max_length=50)),
                ('skills', models.TextField()),
                ('description', models.TextField()),
                ('last_date', models.DateField()),
            ],
        ),
    ]
