# Generated by Django 6.1 on 2026-08-20 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0001_initial'),
        ('recruiter', '0002_remove_job_last_date_job_posted_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ats_score', models.FloatField(default=0)),
                ('matched_skills', models.TextField(blank=True, default='')),
                ('missing_skills', models.TextField(blank=True, default='')),
                ('analysis', models.TextField(blank=True, default='')),
                ('analyzed_date', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_match', to='candidate.jobapplication')),
            ],
        ),
    ]
